In [ ]:
total = 0
count = 0

numbers = input('Enter the number : (<Enter Key> to  quit)')
while numbers != '':
  try:
    x = float(numbers)
    count =+ 1
    total = total + x 
  except ValueError:
    print('Not a number! Ignored...')
  numbers = input('Enter the number : (<Enter Key> to quit)')
avg = total / count 
print('\n average is',avg)
  

Enter the number : (<Enter Key> to  quit)4
Enter the number : (<Enter Key> to quit)5
Enter the number : (<Enter Key> to quit)6
Enter the number : (<Enter Key> to quit)7
Enter the number : (<Enter Key> to quit)

 average is 22.0


In [ ]:
def numbers():
  X = []
  while True:
    number = input('Enter a number (<Enter Key> to quit)')
    while number !="":
      try:
        x = float(number)
        X.append(x)   #Python list ->sequence type : Dynamic Array
      except ValueError:
        print('>>> Not a Number! ignored...')
      number = input('Enter a number (<Enter Key> to quit)')
    if len(X) > 1:
      return X
X = numbers()

print('X : ',X)

total = 0.0
for i in range(len(X)):
  total = total + X[i]
mean = total / len(X)

print('sum of X : ',total)

def median(nums):
  nums.sort()
  size = len(nums)
  p = size // 2   #몫 연산자 (//) - > size 7 일때 우리가 원하는 값은 3 not 3.5
  if size % 2 ==0:
    pr = p
    pl = p-1
    mid = float((nums[pl]+nums[pr])/2)
  else:
    mid = nums[p]
  return mid

print('X : ',X)
median(X)

def means(nums):
  total = 0.0
  for i in range(len(nums)):
    total = total + nums[i]
    return total / len(nums)

means(X)

avg = means(X)

def std_dev(nums,avg):
  texp = 0.0
  for i in range(len(nums)):
    texp = texp + (nums[i] - avg) ** 2
    return (texp/len(nums)) ** 0.5

std_dev(X,avg)

Enter a number (<Enter Key> to quit)3
Enter a number (<Enter Key> to quit)4
Enter a number (<Enter Key> to quit)5
Enter a number (<Enter Key> to quit)
X :  [3.0, 4.0, 5.0]
sum of X :  12.0
X :  [3.0, 4.0, 5.0]


4.0

In [ ]:
def main():
  med = median(X)
  avg = means(X)
  std = std_dev(X,avg)
  print('당신이 입력한 숫자{}의 '.format(X))
  print('중앙값은{}, 평균은{}, 표준편차는{} 입니다.'.format(med,avg,std))

In [ ]:
def numbers():
  X = []
  while True:
    number = input('Enter a number (<Enter Key> to quit)')
    while number !="":
      try:
        x = float(number)
        X.append(x)   #Python list ->sequence type : Dynamic Array
      except ValueError:
        print('>>> Not a Number! ignored...')
      number = input('Enter a number (<Enter Key> to quit)')
    if len(X) > 1:
      return X

def median(nums):
  nums.sort()
  size = len(nums)
  p = size // 2   #몫 연산자 (//) - > size 7 일때 우리가 원하는 값은 3 not 3.5
  if size % 2 ==0:
    pr = p
    pl = p-1
    mid = float((nums[pl]+nums[pr])/2)
  else:
    mid = nums[p]
  return mid

def means(nums):
  total = 0.0
  for i in range(len(nums)):
    total = total + nums[i]
    return total / len(nums)

def std_dev(nums,avg):
  texp = 0.0
  for i in range(len(nums)):
    texp = texp + (nums[i] - avg) ** 2
    return (texp/len(nums)) ** 0.5

def main():
  med = median(X)
  avg = means(X)
  std = std_dev(X,avg)
  print('당신이 입력한 숫자{}의 '.format(X))
  print('중앙값은{}, 평균은{}, 표준편차는{} 입니다.'.format(med,avg,std))

if __name__ == '__main__':
  main()

In [ ]:
import array as arr

mylist = [1,2,3]
print(type(mylist))

mylist.append('4')
print(mylist)

mylist.insert(1,5)
print(mylist)

myarray = arr.array('i',[1,2,3])
print(type(myarray))

# myarray.append('4')
print(myarray)
#Error code : integer is required (got type str)

myarray.insert(1,5)
print(myarray)

# List : built- in / mixed elements type
# Array : import needed / all element have to have same type and size

<class 'list'>
[1, 2, 3, '4']
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


In [ ]:
import numpy as np

A = np.arange(5)
B = np.array([0,1,2,3,4])

C = np.array([0,1,2,3,'4'])
# numpy.ndarry can only have same type elements

D = np.ndarray((5,),np.int64,np.array([0,1,2,3,4]))

print(A)
print(type(A))
print('---------------------------------')
print(B)
print(type(B))
print('---------------------------------')
print(C)
print(type(C))
print('---------------------------------')
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
---------------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
---------------------------------
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
---------------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
A = np.arange(10).reshape(2,5)

print('행렬의 모양 : ',A.shape)
print('행렬의 축 개수 : ',A.ndim)
print('행렬 내의 원소 개수 : ',A.size)

행렬의 모양 :  (2, 5)
행렬의 축 개수 :  2
행렬 내의 원소 개수 :  10


In [ ]:
A = np.arange(10)
print('A: ', A)
B = np.arange(10).reshape(2,5)
print('B: ', B)
C = np.arange(10).reshape(3,3)  # 이 줄에서 에러가 날 것입니다.
print('C: ', C)

# before and after reshape np.size has to be the same

In [ ]:
A = np.arange(6).reshape(2,3)
print(A)
print(A.dtype)
print(type(A))
print('----------------------------')

B = np.array([0,1,2,3,4,5])
print(B)
print(B.dtype)
print(type(B))
print('----------------------------')

C = np.array([0,1,2,3,'4',5])
print(C)
print(C.dtype)
print(type(C))
print('----------------------------')

D = np.array([0,1,2,3,[4,5],6])
print(D)
print(D.dtype)
print(type(D))
print('----------------------------')

# .dtype : shows type of items in numpy ndarray
# Creating an ndarray from ragged nested sequences is deprecated

E = np.array([0,1,2,3,[4,5],6],dtype=object)
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
----------------------------
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
----------------------------
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
----------------------------
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>
----------------------------
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [ ]:
C = np.array([0,1,2,3,'4',5])
print(C[0])
print(type(C[0]))
print(C[4])
print(type(C[4]))
print('--------------------------------')

D = np.array([0,1,2,3,[4,5],6],dtype=object)
print(D[0])
print(type(D[0]))
print(D[4])
print(type(D[4]))

0
<class 'numpy.str_'>
4
<class 'numpy.str_'>
--------------------------------
0
<class 'int'>
[4, 5]
<class 'list'>


In [ ]:
A = np.eye(3)  
#단위행렬
B = np.zeros([2,3])
#0행렬
C = np.ones([3,3])
#1행렬
print(A)
print(B)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.arange(9).reshape(3,3)
print(A)

print(A*2)

print(A+2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
A = np.arange(9).reshape(3,3)
B = np.array([1,2,3]) #1*3 Mattrix
print('A : ',A)
print('B : ',B)
print('\nA+B : ', A+B)

C = np.array([[1],[2],[3]]) #3*1 Mattrix 
print('A : ',A)
print('C : ',C)
print('\nA+C : ', A+C)

D = np.array([1,2])
print('A : ',A)
print('D : ',D)
print('\nA+D : ', A+D)
#Error Code : Value Error -> operands could not be broadcast together

A :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
B :  [1 2 3]

A+B :  [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
A :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
C :  [[1]
 [2]
 [3]]

A+C :  [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [ ]:
print([1,2]+[3,4])
print([1,2]+3)

# Error Code : Type Error : can only concatenate list to list

print(np.array([1,2])+np.array([3,4]))
print(np.array([1,2])+3)

[4 6]
[4 5]


In [ ]:
A = np.arange(9).reshape(3,3)
print('A : ',A)
B = A[0]
print('B : ',B)

print(A[0,1])
print(B[1])

print(A[:-1])

A :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
B :  [0 1 2]
1
1
[[0 1 2]
 [3 4 5]]


In [ ]:
# Random

print(np.random.random()) 
#  a random number in format of float

print(np.random.randint(0,10)) 
# a random number in format of integer

print(np.random.choice([0,1,2,3,4,5,6,7.8,9])) 
# choose one in random among the list items

0.7680714966196122
5
9.0


In [ ]:
print(np.random.permutation(10))
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))
# Create a ramdom matrix(or list/array)

print(np.random.normal(loc=0,scale=1,size=5))
# Normal distribution (average=loc, standard deviation=scale)
print(np.random.uniform(low=-1,high=1,size=5))
# Uniform distribution 

[8 4 2 5 0 9 3 1 6 7]
[8 4 0 1 6 7 3 9 5 2]
[ 0.01187773  0.03816465  0.74605825  0.38171814 -0.02214604]
[-0.85965827  0.7077318  -0.40580582 -0.20552359  0.03483815]


In [ ]:
# Transpose Matrix

A = np.arange(24).reshape(2,3,4)
print('A : ',A)
print('A 의 전치행렬 : ',A.T)
print('A 의 전치행렬의 shape : ',A.T.shape)


B = np.transpose(A,(2,0,1))
print('A : ',A)
print('B : ',B)
print('B.shape: ',B.shape)

A :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
A 의 전치행렬 :  [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
A 의 전치행렬의 shape :  (4, 3, 2)
A :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B :  [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
B.shape:  (4, 2, 3)


In [ ]:
import numpy as np

def numbers():
    X = []
    number = input("Enter a number (<Enter key> to quit)") 
    # 하지만 2개 이상의 숫자를 받아야 한다는 제약조건을 제외
    while number != "":
        try:
            x = float(number)
            X.append(x)
        except ValueError:
            print('>>> NOT a number! Ignored..')
        number = input("Enter a number (<Enter key> to quit)")
    return X

def main():
    nums = numbers()       # 이것은 파이썬 리스트입니다. 
    num = np.array(nums)   # 리스트를 Numpy ndarray로 변환합니다.
    print("합", num.sum())
    print("평균값",num.mean())
    print("표준편차",num.std())
    print("중앙값",np.median(num))   # num.median() 이 아님에 유의해 주세요.

main()

In [ ]:
## How to handle different types of data in Numpy ##

# Audio and Timeseries
# An audio file is a one-dimensional arrya of samples. 
# load the file into a Numpy array and call 'audio' and get audio[:44110]

# Images
# An image is a matrix of pixels of size(height*width)
# - black&white iamge : each pixel can be represented by a single number
#                       tell Numpy to get image[:10,:10]
# - colored image : each pixel is represented by three numbers ( a vaule for each of red, green and blue)
#                   which means that we need a 3rd dimension 
#                   (colored image is represented by an ndarray of dimensions(height*weight*3))

# Language
# The numeric representation of text requires a step of building a vocabulary and an embeding step
# A model needs to look at a large amount of text before it can numerically represent the words
# [batch_size,sequence_length,embeding_size]


In [ ]:
import matplotlib as mpl
import PIL

print(f'# matplotlib: {mpl.__version__}')
print(f'# PIL: {PIL.__version__}')

# matplotlib: 3.2.2
# PIL: 7.1.2


In [ ]:
from PIL import Image, ImageColor
import os
# img_path = content/drive/MyDrive/newyork.jpeg
img = Image.open('/content/drive/MyDrive/newyork.jpeg')
print(type(img))
print(img)

W,H = img.size
print((W,H))    # size
print(img.format)
print(img.mode)

print(img.crop((30,30,100,100))) # 가로 세로의 시작점과 종료점 총 4개 입력

cropped_img_path = '/content/drive/MyDrive/newyork_cropped.jpeg'
img.crop((30,30,100,100)).save(cropped_img_path)
print('저장완료!')

<class 'PIL.JpegImagePlugin.JpegImageFile'>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=212x300 at 0x7F9388C3B250>
(212, 300)
JPEG
RGB
저장완료!


In [ ]:
import numpy as np
img_arr = np.array(img)
print(type(img))
print(type(img_arr))
print(img_arr.shape)
print(img_arr.ndim)

img_arr

<class 'PIL.JpegImagePlugin.JpegImageFile'>
<class 'numpy.ndarray'>
(300, 212, 3)
3


array([[[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       [[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       [[133, 180, 250],
        [133, 180, 250],
        [133, 180, 250],
        ...,
        [133, 180, 250],
        [133, 180, 250],
        [133, 180, 250]],

       ...,

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]],

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]],

       [[164, 199, 255],
        [164, 199, 255],
        [164, 199, 255],
        ...,
        [164, 199, 255],
        [164, 199, 255],
        [164, 199, 255]]

In [ ]:
from PIL import Image, ImageColor
import numpy as np

import os
img_path = '/content/drive/MyDrive/newyork.jpeg'
img_g = Image.open(img_path).convert('L')
img_g

img_g_arr = np.array(img_g)
print(type(img_g_arr))
print(img_g_arr.shape)
print(img_g_arr.ndim)

img_g_arr

red = ImageColor.getcolor('RED','RGB')
reda = ImageColor.getcolor('red','RGBA')
yellow = ImageColor.getcolor('yellow','RGB')
print(red)
print(reda)
print(yellow)

<class 'numpy.ndarray'>
(300, 212)
2
(255, 0, 0)
(255, 0, 0, 255)
(255, 255, 0)


In [ ]:
# 파이썬 dict 로 표현한 전화번호부입니다. 
Country_PhoneNumber = {'Korea': 82, 'America': 1, 'Swiss': 41, 'Italy': 39, 'Japan': 81, 'China': 86, 'Rusia': 7}
Country_PhoneNumber['Korea']  # 키를 가지고 값을 조회할 수 있습니다.

82

In [ ]:
treasure_box = {'rope':2, 
                'apple':10, 
                'torch': 6, 
                'gold coin': 50, 
                'knife': 1, 
                'arrow': 30}

def display_stuff(treasure_box):
    print("Congraturation!! you got a treasure box")
    for k, v in treasure_box.items():
        print("you have {} {}pcs".format(k, v))
display_stuff(treasure_box)

coin_per_treasure = {'rope':1,
        'apple':2,
        'torch': 2,
        'gold coin': 5, 
        'knife': 30,
        'arrow': 1}

def total_silver(treasure_box, coin_per_treasure):
    total_coin = 0
    for treasure in treasure_box:
        coin = coin_per_treasure[treasure] * treasure_box[treasure]
        print("{} : {}coins/pcs * {}pcs = {} coins".format(
          treasure, coin_per_treasure[treasure], treasure_box[treasure], coin))
        total_coin += coin
    print('total_coin : ', total_coin)
total_silver(treasure_box, coin_per_treasure)

Congraturation!! you got a treasure box
you have rope 2pcs
you have apple 10pcs
you have torch 6pcs
you have gold coin 50pcs
you have knife 1pcs
you have arrow 30pcs
rope : 1coins/pcs * 2pcs = 2 coins
apple : 2coins/pcs * 10pcs = 20 coins
torch : 2coins/pcs * 6pcs = 12 coins
gold coin : 5coins/pcs * 50pcs = 250 coins
knife : 30coins/pcs * 1pcs = 30 coins
arrow : 1coins/pcs * 30pcs = 30 coins
total_coin :  344


In [ ]:
treasure_box = {'rope': {'coin': 1, 'pcs': 2},
                'apple': {'coin': 2, 'pcs': 10},
                'torch': {'coin': 2, 'pcs': 6},
                'gold coin': {'coin': 5, 'pcs': 50},
                'knife': {'coin': 30, 'pcs': 1},
               	'arrow': {'coin': 1, 'pcs': 30}
               }
treasure_box['rope']